// src/app/features/flashcard-generator/components/word-input/word-input.component.ts
import { ChangeDetectionStrategy, Component, output, signal } from '@angular/core';
import { FormControl, ReactiveFormsModule } from '@angular/forms';
import { LucideAngularModule, X } from 'lucide-angular';
import { BadgeComponent } from '../../../../shared/components/badge/badge.component';
import {
  CardComponent,
  CardContentDirective,
  CardDescriptionDirective,
  CardHeaderDirective,
  CardTitleDirective,
} from '../../../../shared/components/card/card.component';
import { ButtonDirective } from '../../../../shared/directives/button/button.directive';
import { TextareaDirective } from '../../../../shared/directives/textarea/textarea.directive';

@Component({
  selector: 'app-word-input',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [
    ReactiveFormsModule,
    ButtonDirective,
    CardComponent,
    CardHeaderDirective,
    CardTitleDirective,
    CardDescriptionDirective,
    CardContentDirective,
    TextareaDirective,
    BadgeComponent,
    LucideAngularModule,
  ],
  templateUrl: './word-input.component.html',
})
export class WordInputComponent {
  // Constants
  protected readonly ICONS = {
    X,
  };

  // Outputs
  public readonly wordsSubmit = output<string[]>();

  // Public State
  protected readonly inputControl = new FormControl('', { nonNullable: true });

  protected readonly words = signal<string[]>([]);

  protected parseWords() {
    const text = this.inputControl.value;
    const parsed = text
      .split(/[\n,]+/)
      .map((w) => w.trim())
      .filter((w) => w.length > 0);

    this.words.set(parsed);
  }

  protected setWords(newWords: string[]) {
    this.words.set(newWords);
  }

  protected removeWord(index: number) {
    this.words.update((current) => current.filter((_, i) => i !== index));
  }

  protected submit() {
    if (this.words().length > 0) {
      this.wordsSubmit.emit(this.words());
    }
  }
}

<lib-card class="mx-auto w-full max-w-2xl" [className]="'bg-background'">
  <lib-card-header>
    <lib-card-title class="text-heading-20 font-semibold">Flashcard Generator</lib-card-title>
    <lib-card-description class="text-label-14">
      Enter words separated by commas, whitespace, or new lines
    </lib-card-description>
  </lib-card-header>
  <lib-card-content class="flex flex-col gap-6">
    <div class="flex items-center gap-3 rounded-md bg-secondary p-3 text-sm text-muted-foreground">
      <lucide-icon class="size-4 shrink-0" [img]="ICONS.Info" />
      <p>Currently optimized for English vocabulary. Multi-language support coming soon!</p>
    </div>

    <div class="flex flex-col gap-3">
      <textarea
        class="min-h-32 resize-none font-mono text-sm"
        [formControl]="inputControl"
        name="words"
        appTextarea
        placeholder="apple, banana, cherry&#10;dog, cat, bird"
      ></textarea>
      <button class="w-full justify-center" (click)="parseWords()" appButton variant="secondary">
        Parse Words
      </button>
    </div>

    @if (error()) {
      <p class="text-sm text-destructive">{{ error() }}</p>
    }

    @if (words().length > 0) {
      <div class="flex flex-col gap-3">
        <div class="flex items-center justify-between">
          <p class="text-label-14">
            <strong>
              {{ words().length }} {{ words().length === 1 ? 'word' : 'words' }} parsed
            </strong>
          </p>
          <button
            class="h-8 px-2 text-muted-foreground"
            (click)="setWords([])"
            appButton
            variant="ghost"
            size="sm"
            shape="rounded"
          >
            Clear all
          </button>
        </div>
        <div class="flex flex-wrap gap-2">
          @for (word of words(); track i; let i = $index; let first = $first) {
            <app-badge
              class="inline-flex items-center py-1 pr-1 text-sm font-normal"
              [class.pl-0]="first"
              [class.pl-1]="!first"
              variant="secondary"
            >
              {{ word }}
              <button
                class="ml-2 flex cursor-pointer items-center border-none bg-transparent p-0 text-foreground-light hover:text-destructive focus:outline-none"
                [attr.aria-label]="'Remove ' + word"
                (click)="removeWord(i)"
              >
                <lucide-icon class="size-3" [img]="ICONS.X" />
              </button>
            </app-badge>
          }
        </div>
        <button class="w-full justify-center" [disabled]="isLoading()" (click)="submit()" appButton>
          @if (isLoading()) {
            Generating...
          } @else {
            Create Flashcards
          }
        </button>
      </div>
    }
  </lib-card-content>
</lib-card>

// src/features/flashcard-generator/components/word-input.tsx
import { useState } from 'react';
import { Info, X } from 'lucide-react';

import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Spinner } from '@/components/ui/spinner';
import { Textarea } from '@/components/ui/textarea';
import type { Flashcard } from '@/models/flashcard';
import { ENGLISH_PICTURE_WORDS } from '@/models/flashcard';
import { generateFlashcards } from '@/services/gemini-service';
import { useLanguageStore, useSettingsStore } from '@/stores';

export interface WordInputProps {
  onGenerate: (flashcards: Flashcard[]) => void;
}

export function WordInput({ onGenerate }: WordInputProps) {
  const [inputText, setInputText] = useState('');
  const [words, setWords] = useState<string[]>([]);
  const [isGenerating, setIsGenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const { apiKey } = useSettingsStore();
  const { targetLanguage, nativeLanguage } = useLanguageStore();

  const handleParseWords = () => {
    const parsed = [
      ...new Set(
        inputText
          .split(/[\s,]+/)
          .map((w) => w.trim())
          .filter((w) => w.length > 0),
      ),
    ];
    setWords(parsed);
  };

  const handleRemoveWord = (indexToRemove: number) => {
    setWords((prev) => prev.filter((_, index) => index !== indexToRemove));
  };

  const handleClearWords = () => {
    setWords([]);
  };

  const handleSubmit = async () => {
    if (words.length === 0) return;

    setIsGenerating(true);
    setError(null);

    try {
      const apiResults = await generateFlashcards(
        words,
        apiKey,
        ENGLISH_PICTURE_WORDS,
        targetLanguage,
        nativeLanguage,
      );

      const newFlashcards: Flashcard[] = apiResults.map((fieldValues) => ({
        id: crypto.randomUUID(),
        noteTypeId: ENGLISH_PICTURE_WORDS.id,
        fieldValues,
        selectedImages: [],
      }));

      onGenerate(newFlashcards);
    } catch (err) {
      if (err instanceof Error) {
        setError(err.message);
      } else {
        setError('An unknown error occurred while generating flashcards.');
      }
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <div className="mx-auto w-full max-w-2xl">
      <div className="flex flex-col gap-8">
        <div className="space-y-1.5">
          <h2 className="text-heading-20">Flashcard Generator</h2>
          <p className="text-[14px] text-muted-foreground">
            Enter words separated by commas, whitespace, or new lines
          </p>
        </div>

        <div className="bg-accent/60 flex items-start gap-3 rounded-md px-4 py-3 text-[13px] text-muted-foreground">
          <Info className="mt-0.5 size-4 shrink-0" />
          <p>Currently optimized for English vocabulary. Multi-language support coming soon.</p>
        </div>

        <div className="flex flex-col gap-3">
          <Textarea
            className="min-h-32 resize-none font-mono text-[13px]"
            value={inputText}
            onChange={(e) => setInputText(e.target.value)}
            placeholder="apple, banana, cherry&#10;dog, cat, bird"
            name="words"
          />
          <Button className="w-full justify-center" onClick={handleParseWords} variant="secondary">
            Parse Words
          </Button>
        </div>

        {error && (
          <div className="border-destructive/20 bg-destructive/5 rounded-md border px-4 py-3 text-[14px] text-destructive">
            {error}
          </div>
        )}

        {words.length > 0 && (
          <div className="flex animate-content-enter flex-col gap-4">
            <div className="flex items-center justify-between">
              <p className="text-[14px] font-medium">
                {words.length} {words.length === 1 ? 'word' : 'words'} parsed
              </p>
              <Button
                className="h-8 px-2 text-muted-foreground"
                onClick={handleClearWords}
                variant="ghost"
                size="sm"
              >
                Clear all
              </Button>
            </div>
            <div className="flex flex-wrap gap-2">
              {words.map((word, index) => (
                <Badge
                  key={`${word}-${index}`}
                  className="inline-flex items-center gap-1.5 py-1.5 pl-3 pr-1.5 text-[13px] font-normal"
                  variant="secondary"
                >
                  {word}
                  <button
                    className="text-foreground/40 hover:bg-destructive/10 focus-visible:ring-ring/40 flex size-5 cursor-pointer items-center justify-center rounded border-none bg-transparent transition-colors hover:text-destructive focus-visible:outline-none focus-visible:ring-2"
                    aria-label={`Remove ${word}`}
                    onClick={() => handleRemoveWord(index)}
                  >
                    <X className="size-3" />
                  </button>
                </Badge>
              ))}
            </div>
            <Button
              className="w-full justify-center"
              disabled={isGenerating}
              onClick={handleSubmit}
            >
              {isGenerating ? (
                <>
                  <Spinner className="mr-2" size="sm" />
                  Generating…
                </>
              ) : (
                'Create Flashcards'
              )}
            </Button>
          </div>
        )}
      </div>
    </div>
  );
}
