// src/features/flashcard-generator/components/flashcard-editor.tsx
import { useEffect, useMemo, useState } from 'react';

import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import type { Flashcard, FlashcardImage, NoteType } from '@/models/flashcard';

interface FlashcardEditorProps {
  flashcard: Flashcard;
  noteType: NoteType;
  open: boolean;
  onSave: (updated: Flashcard) => void;
  onClose: () => void;
}

export function FlashcardEditor({
  flashcard,
  noteType,
  open,
  onSave,
  onClose,
}: FlashcardEditorProps) {
  const [localValues, setLocalValues] = useState<Record<string, string>>({});
  const [localImages, setLocalImages] = useState<FlashcardImage[]>([]);

  const editableFields = useMemo(
    () => noteType.fields.filter((field) => field.fieldType !== 'image'),
    [noteType.fields],
  );

  useEffect(() => {
    if (!open) {
      return;
    }

    setLocalValues({ ...flashcard.fieldValues });
    setLocalImages([...flashcard.selectedImages]);
  }, [open, flashcard]);

  const handleFieldChange = (fieldName: string, value: string) => {
    setLocalValues((current) => ({ ...current, [fieldName]: value }));
  };

  const handleRemoveImage = (imageId: string) => {
    setLocalImages((current) => current.filter((image) => image.id !== imageId));
  };

  const handleSave = () => {
    onSave({
      ...flashcard,
      fieldValues: localValues,
      selectedImages: localImages,
    });
  };

  return (
    <Dialog open={open} onOpenChange={(nextOpen) => !nextOpen && onClose()}>
      <DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-2xl">
        <DialogHeader>
          <DialogTitle>Edit Flashcard</DialogTitle>
          <DialogDescription>Update fields and remove images before export.</DialogDescription>
        </DialogHeader>

        <div className="space-y-6">
          {localImages.length > 0 ? (
            <div className="space-y-3">
              <p className="text-[14px] font-medium">Selected Images</p>
              <div className="grid grid-cols-2 gap-3 sm:grid-cols-3">
                {localImages.map((image) => (
                  <div
                    key={image.id}
                    className="group relative overflow-hidden rounded-lg border border-border"
                  >
                    <img
                      src={image.thumbnail || image.url || '/placeholder.svg'}
                      alt={image.title}
                      className="h-24 w-full object-cover"
                    />
                    <Button
                      type="button"
                      variant="destructive"
                      size="sm"
                      className="absolute right-2 top-2 h-7 px-2 opacity-0 transition-opacity group-hover:opacity-100"
                      onClick={() => handleRemoveImage(image.id)}
                    >
                      Remove
                    </Button>
                  </div>
                ))}
              </div>
            </div>
          ) : null}

          <div className="space-y-4">
            {editableFields.map((field) => (
              <div key={field.name} className="space-y-2">
                <label htmlFor={field.name} className="text-[14px] font-medium">
                  {field.name}
                </label>
                {field.fieldType === 'textarea' ? (
                  <Textarea
                    id={field.name}
                    value={localValues[field.name] || ''}
                    onChange={(event) => handleFieldChange(field.name, event.target.value)}
                  />
                ) : (
                  <Input
                    id={field.name}
                    value={localValues[field.name] || ''}
                    onChange={(event) => handleFieldChange(field.name, event.target.value)}
                  />
                )}
              </div>
            ))}
          </div>
        </div>

        <DialogFooter>
          <Button type="button" variant="outline" onClick={onClose}>
            Cancel
          </Button>
          <Button type="button" onClick={handleSave}>
            Save
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

// src/app/features/flashcard-generator/components/flashcard-editor/flashcard-editor.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  effect,
  input,
  output,
  signal,
} from '@angular/core';
import { FormControl, FormGroup, ReactiveFormsModule } from '@angular/forms';
import {
  CardComponent,
  CardContentDirective,
  CardDescriptionDirective,
  CardFooterDirective,
  CardHeaderDirective,
  CardTitleDirective,
} from '@shared/components';
import { ButtonDirective, InputDirective, TextareaDirective } from '@shared/directives';
import { LucideAngularModule, X } from 'lucide-angular';
import { Flashcard, FlashcardImage } from '../../models/flashcard.types';
import { NoteType } from '../../models/note-type.model';

@Component({
  selector: 'app-flashcard-editor',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [
    ReactiveFormsModule,
    ButtonDirective,
    CardComponent,
    CardHeaderDirective,
    CardTitleDirective,
    CardDescriptionDirective,
    CardContentDirective,
    CardFooterDirective,
    InputDirective,
    TextareaDirective,
    LucideAngularModule,
  ],
  templateUrl: './flashcard-editor.component.html',
})
export class FlashcardEditorComponent {
  // Constants
  protected readonly ICONS = {
    X,
  };

  // Inputs
  public readonly flashcard = input<Flashcard | null>(null);

  public readonly noteType = input.required<NoteType>();

  // Outputs
  public readonly save = output<Flashcard>();

  public readonly cancelEdit = output();

  // Public State - dynamic form group
  protected readonly form = signal<FormGroup>(new FormGroup({}));

  protected readonly editedImages = signal<FlashcardImage[]>([]);

  protected readonly formReady = signal(false);

  protected readonly editableFields = computed(() => {
    if (!this.formReady()) {
      return [];
    }
    return this.noteType().fields.filter((f) => f.fieldType !== 'image');
  });

  // Constructor
  public constructor() {
    effect(() => {
      const card = this.flashcard();
      const noteType = this.noteType();
      if (card && noteType) {
        this.initializeForm();
      }
    });
  }

  private initializeForm() {
    const card = this.flashcard();
    const noteType = this.noteType();
    if (!card || !noteType) return;

    // Reset form ready state before rebuilding
    this.formReady.set(false);

    // Build form controls dynamically from note type fields
    const controls: Record<string, FormControl<string>> = {};
    for (const field of noteType.fields) {
      // Skip image fields - they are handled separately
      if (field.fieldType !== 'image') {
        controls[field.name] = new FormControl(card.fieldValues[field.name] || '', {
          nonNullable: true,
        });
      }
    }

    this.form.set(new FormGroup(controls));
    this.editedImages.set([...card.selectedImages]);
    this.formReady.set(true);
  }

  protected removeImage(imageId: string) {
    this.editedImages.update((current) => current.filter((img) => img.id !== imageId));
  }

  protected discardChanges() {
    this.cancelEdit.emit();
  }

  protected saveChanges() {
    const card = this.flashcard();
    const formGroup = this.form();
    if (!card || formGroup.invalid) return;

    // Build fieldValues from form controls
    const fieldValues: Record<string, string> = {};
    for (const fieldName of Object.keys(formGroup.controls)) {
      fieldValues[fieldName] = (formGroup.get(fieldName) as FormControl<string>).value;
    }

    const updatedFlashcard: Flashcard = {
      ...card,
      fieldValues,
      selectedImages: this.editedImages(),
    };

    this.save.emit(updatedFlashcard);
  }
}

<lib-card class="max-h-[90vh] w-full" className="flex flex-col h-full overflow-hidden">
  <lib-card-header class="flex-none">
    <lib-card-title>Edit Flashcard</lib-card-title>
    <lib-card-description>Make changes to your flashcard details.</lib-card-description>
  </lib-card-header>

  <lib-card-content class="flex min-h-0 flex-1 flex-col gap-6 overflow-y-auto">
    <!-- Images -->
    @if (editedImages().length > 0) {
      <div class="flex flex-col gap-2">
        <span class="text-sm font-medium">Selected Images</span>
        <div class="grid grid-cols-2 gap-4 sm:grid-cols-3">
          @for (image of editedImages(); track image.id) {
            <div class="relative aspect-video rounded-lg bg-muted">
              <img
                class="h-full w-full rounded-lg object-cover"
                [src]="image.thumbnail || '/placeholder.svg'"
                [alt]="image.title"
              />
              <button
                class="absolute top-2 right-2 size-5 justify-center p-0"
                (click)="removeImage(image.id)"
                appButton
                variant="destructive"
                size="custom"
                aria-label="Remove image"
                shape="rounded"
              >
                <lucide-icon class="size-4" [img]="ICONS.X" />
              </button>
            </div>
          }
        </div>
      </div>
    }

    <!-- Dynamic Form Fields -->
    <div class="grid gap-4" [formGroup]="form()">
      @for (field of editableFields(); track field.name) {
        <div class="flex flex-col gap-2">
          <label class="text-sm font-medium" [for]="field.name">{{ field.name }}</label>
          @if (field.fieldType === 'textarea') {
            <textarea [id]="field.name" [formControlName]="field.name" appTextarea></textarea>
          } @else {
            <input [id]="field.name" [formControlName]="field.name" appInput />
          }
        </div>
      }
    </div>
  </lib-card-content>

  <lib-card-footer class="flex-none justify-end gap-2">
    <button (click)="discardChanges()" appButton variant="secondary">Discard</button>
    <button (click)="saveChanges()" appButton>Save Changes</button>
  </lib-card-footer>
</lib-card>
