// src/features/flashcard-generator/components/image-selector.tsx
import { useCallback, useEffect, useMemo, useState } from 'react';
import { Check, Search } from 'lucide-react';

import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Spinner } from '@/components/ui/spinner';
import type { Flashcard, FlashcardImage, NoteType } from '@/models/flashcard';
import { searchImages } from '@/services/image-search-service';
import type { ImageSearchResult } from '@/services/image-search-service';
import { GOOGLE_CSE_ID, useSettingsStore } from '@/stores';

interface ImageSelectorProps {
  flashcard: Flashcard;
  noteType: NoteType;
  onSelect: (flashcard: Flashcard) => void;
}

function getWordFromFlashcard(flashcard: Flashcard, noteType: NoteType): string {
  const firstField = noteType.fields[0];

  if (!firstField) {
    return '';
  }

  return flashcard.fieldValues[firstField.name] ?? '';
}

function toFlashcardImage(result: ImageSearchResult): FlashcardImage {
  return {
    id: result.link,
    url: result.link,
    thumbnail: result.thumbnailLink,
    title: 'Selected image',
  };
}

function resolveSelectedImages(
  selectedUrls: string[],
  searchResults: ImageSearchResult[],
  existingSelected: FlashcardImage[],
): FlashcardImage[] {
  return selectedUrls.map((url) => {
    const fromResults = searchResults.find((result) => result.link === url);
    if (fromResults) {
      return toFlashcardImage(fromResults);
    }

    const fromExisting = existingSelected.find((image) => image.url === url);
    if (fromExisting) {
      return fromExisting;
    }

    return {
      id: url,
      url,
      thumbnail: url,
      title: 'Selected image',
    };
  });
}

export function ImageSelector({ flashcard, noteType, onSelect }: ImageSelectorProps) {
  const { googleCseApiKey } = useSettingsStore();

  const [searchQuery, setSearchQuery] = useState('');
  const [images, setImages] = useState<ImageSearchResult[]>([]);
  const [selectedImages, setSelectedImages] = useState<string[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const cardWord = useMemo(() => getWordFromFlashcard(flashcard, noteType), [flashcard, noteType]);

  const runSearch = useCallback(
    async (query: string) => {
      const trimmedQuery = query.trim();

      if (!trimmedQuery) {
        setImages([]);
        setError(null);
        return;
      }

      if (!googleCseApiKey) {
        setImages([]);
        setError('Google CSE API key is missing. Add it in Settings to search images.');
        return;
      }

      setIsLoading(true);
      setError(null);

      try {
        const results = await searchImages(trimmedQuery, googleCseApiKey, GOOGLE_CSE_ID);
        setImages(results);
      } catch (err) {
        if (err instanceof Error) {
          setError(err.message);
        } else {
          setError('Image search failed. Please try again.');
        }
      } finally {
        setIsLoading(false);
      }
    },
    [googleCseApiKey],
  );

  useEffect(() => {
    const initialQuery = cardWord.trim();
    setSearchQuery(initialQuery);
    setSelectedImages(flashcard.selectedImages.map((image) => image.url));
    void runSearch(initialQuery);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [cardWord, flashcard.id, runSearch]);

  const emitSelectedFlashcard = useCallback(
    (nextSelectedUrls: string[]) => {
      const nextSelectedImages = resolveSelectedImages(
        nextSelectedUrls,
        images,
        flashcard.selectedImages,
      );

      onSelect({
        ...flashcard,
        selectedImages: nextSelectedImages,
      });
    },
    [flashcard, images, onSelect],
  );

  const handleToggleImage = useCallback(
    (imageUrl: string) => {
      setSelectedImages((previousSelected) => {
        const isSelected = previousSelected.includes(imageUrl);

        let nextSelected = previousSelected;
        if (isSelected) {
          nextSelected = previousSelected.filter((selectedUrl) => selectedUrl !== imageUrl);
        } else if (previousSelected.length < 2) {
          nextSelected = [...previousSelected, imageUrl];
        }

        if (nextSelected !== previousSelected) {
          emitSelectedFlashcard(nextSelected);
        }

        return nextSelected;
      });
    },
    [emitSelectedFlashcard],
  );

  const handleSearch = useCallback(async () => {
    await runSearch(searchQuery);
  }, [runSearch, searchQuery]);

  return (
    <div className="w-full space-y-6">
      <div className="space-y-1.5">
        <h3 className="text-heading-20">{cardWord || 'Flashcard'}</h3>
        <p className="text-[14px] text-muted-foreground">
          Select up to 2 images for this flashcard.
        </p>
      </div>

      <div className="space-y-4">
        <div className="flex gap-2">
          <Input
            value={searchQuery}
            onChange={(event) => setSearchQuery(event.target.value)}
            onKeyDown={(event) => {
              if (event.key === 'Enter') {
                event.preventDefault();
                void handleSearch();
              }
            }}
            placeholder="Search for images"
          />
          <Button type="button" variant="secondary" onClick={() => void handleSearch()}>
            <Search className="size-4" />
            Search
          </Button>
        </div>

        <p className="text-[13px] text-muted-foreground">
          <span className="font-medium text-foreground">{selectedImages.length}</span> / 2 images
          selected
        </p>

        {isLoading ? (
          <div className="border-border/60 bg-surface-raised/50 flex min-h-56 items-center justify-center rounded-lg border border-dashed">
            <Spinner size="md" />
          </div>
        ) : null}

        {!isLoading && error ? (
          <div className="border-destructive/20 bg-destructive/5 rounded-md border p-4 text-[14px] text-destructive">
            {error}
          </div>
        ) : null}

        {!isLoading && !error && images.length === 0 ? (
          <div className="border-border/60 bg-surface-raised/50 rounded-lg border border-dashed p-8 text-center text-[14px] text-muted-foreground">
            No images found. Try a different search term.
          </div>
        ) : null}

        {!isLoading && !error && images.length > 0 ? (
          <div className="grid grid-cols-2 gap-3 md:grid-cols-3">
            {images.map((image) => {
              const isSelected = selectedImages.includes(image.link);
              const disableNewSelection = !isSelected && selectedImages.length >= 2;

              return (
                <button
                  key={image.link}
                  type="button"
                  className={`group relative aspect-video overflow-hidden rounded-lg border-2 transition-all duration-150 ${
                    isSelected
                      ? 'ring-foreground/15 border-foreground ring-2 ring-offset-2 ring-offset-background'
                      : 'border-border hover:border-border-hover hover:shadow-sm'
                  } ${disableNewSelection ? 'cursor-not-allowed opacity-40' : 'cursor-pointer'}`}
                  onClick={() => handleToggleImage(image.link)}
                  disabled={disableNewSelection}
                >
                  <img
                    src={image.thumbnailLink || image.link}
                    alt=""
                    className="h-full w-full object-cover transition-transform duration-200 group-hover:scale-[1.03]"
                    loading="lazy"
                  />

                  {isSelected ? (
                    <div className="bg-foreground/25 absolute inset-0 flex items-center justify-center">
                      <span className="flex size-8 items-center justify-center rounded-lg bg-foreground text-background shadow-sm">
                        <Check className="size-4" />
                      </span>
                    </div>
                  ) : null}
                </button>
              );
            })}
          </div>
        ) : null}
      </div>
    </div>
  );
}

// src/app/features/flashcard-generator/components/image-selector/image-selector.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  effect,
  inject,
  input,
  output,
  signal,
} from '@angular/core';
import { FormControl, ReactiveFormsModule } from '@angular/forms';
import {
  BadgeComponent,
  CardComponent,
  CardContentDirective,
  CardDescriptionDirective,
  CardHeaderDirective,
  CardTitleDirective,
} from '@shared/components';
import { ButtonDirective, InputDirective } from '@shared/directives';
import { Check, LucideAngularModule, Search } from 'lucide-angular';
import { Flashcard, FlashcardImage } from '../../models/flashcard.types';
import { NoteType, NoteTypeField } from '../../models/note-type.model';
import { IMAGES_PER_PAGE, ImageSearchService } from '../../services/image-search.service';

@Component({
  selector: 'app-image-selector',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [
    ReactiveFormsModule,
    ButtonDirective,
    CardComponent,
    CardHeaderDirective,
    CardTitleDirective,
    CardDescriptionDirective,
    CardContentDirective,
    InputDirective,
    BadgeComponent,
    LucideAngularModule,
  ],
  templateUrl: './image-selector.component.html',
})
export class ImageSelectorComponent {
  // Services
  private readonly imageSearchService = inject(ImageSearchService);

  // Constants
  protected readonly ICONS = {
    Search,
    Check,
  };

  // Inputs
  public readonly flashcard = input.required<Flashcard>();

  public readonly noteType = input.required<NoteType>();

  public readonly currentIndex = input(0);

  public readonly totalCards = input(0);

  // Outputs
  public readonly imagesSelected = output<FlashcardImage[]>();

  public readonly next = output();

  public readonly back = output();

  // Public State
  protected readonly searchControl = new FormControl('', { nonNullable: true });

  protected readonly images = signal<FlashcardImage[]>([]);

  protected readonly selectedImages = signal<FlashcardImage[]>([]);

  protected readonly isLoading = signal(false);

  private imageOffset = 1;

  // Constructor
  public constructor() {
    effect(() => {
      const card = this.flashcard();
      if (card) {
        this.initializeCard();
      }
    });
  }

  protected getFlashcardTitle(): string {
    const titleField = this.noteType().fields.find((f) => f.isTitle);
    return titleField ? this.flashcard().fieldValues[titleField.name] || 'Word' : 'Word';
  }

  private async initializeCard() {
    const card: Flashcard = this.flashcard();
    const titleField: NoteTypeField | undefined = this.noteType().fields.find((f) => f.isTitle);
    const word: string | undefined = titleField ? card.fieldValues[titleField.name] : undefined;

    if (!word) {
      console.error('No word can be used to search for images');
      return;
    }

    this.searchControl.setValue(word);
    this.selectedImages.set(card.selectedImages || []);
    this.imageOffset = 1;

    this.isLoading.set(true);
    const searchImages = await this.imageSearchService.searchImages(word, 1);
    this.images.set(searchImages);
    this.isLoading.set(false);
  }

  protected async search() {
    const term = this.searchControl.value;
    this.imageOffset = 1;
    this.isLoading.set(true);
    const searchImages = await this.imageSearchService.searchImages(term, 1);
    this.images.set(searchImages);
    this.isLoading.set(false);
  }

  protected async loadMore() {
    this.imageOffset += IMAGES_PER_PAGE;
    const term = this.searchControl.value;
    this.isLoading.set(true);
    const moreImages = await this.imageSearchService.searchImages(term, this.imageOffset);
    this.images.update((current) => [...current, ...moreImages]);
    this.isLoading.set(false);
  }

  protected toggleImageSelection(image: FlashcardImage) {
    const isSelected = this.selectedImages().some((img) => img.id === image.id);

    if (isSelected) {
      this.selectedImages.update((current) => current.filter((img) => img.id !== image.id));
    } else {
      if (this.selectedImages().length < 2) {
        this.selectedImages.update((current) => [...current, image]);
      }
    }
  }

  protected isImageSelected(imageId: string): boolean {
    return this.selectedImages().some((img) => img.id === imageId);
  }

  protected navigateNext() {
    this.imagesSelected.emit(this.selectedImages());
    this.next.emit();
  }
}

<div class="mx-auto flex w-full max-w-5xl flex-col gap-6">
  <!-- Progress indicator -->
  <div class="flex items-center justify-between">
    <app-badge class="px-3 py-1.5 text-sm font-medium" variant="secondary">
      Card {{ currentIndex() + 1 }} of {{ totalCards() }}
    </app-badge>
    <p class="text-label-14 text-muted-foreground">
      {{ selectedImages().length }} / 2 images selected
    </p>
  </div>

  <!-- Flashcard info -->
  <lib-card>
    <lib-card-header>
      <lib-card-title class="text-2xl font-semibold">{{ getFlashcardTitle() }}</lib-card-title>
      <lib-card-description class="text-base"
        >Select 1-2 images for this flashcard</lib-card-description
      >
    </lib-card-header>
    <lib-card-content class="flex flex-col gap-4">
      <div class="flex items-center gap-2">
        <input
          class="flex-1"
          [formControl]="searchControl"
          (keydown.enter)="search()"
          appInput
          placeholder="Search images"
        />
        <button class="justify-center" (click)="search()" appButton variant="secondary" size="icon">
          <lucide-icon class="size-5" [img]="ICONS.Search" />
          <span class="sr-only">Search</span>
        </button>
      </div>

      <!-- Image grid -->
      <div class="grid grid-cols-2 gap-4 md:grid-cols-3">
        @for (image of images(); track image.id) {
          <button
            class="relative aspect-video cursor-pointer overflow-hidden rounded-lg border-2 bg-transparent p-0 transition-all duration-150 hover:scale-[1.02] disabled:cursor-not-allowed disabled:opacity-50"
            [class.border-border]="!isImageSelected(image.id)"
            [class.border-foreground]="isImageSelected(image.id)"
            [class.ring-2]="isImageSelected(image.id)"
            [class.ring-foreground]="isImageSelected(image.id)"
            [class.ring-offset-2]="isImageSelected(image.id)"
            [class.ring-offset-background]="isImageSelected(image.id)"
            [class.hover:border-muted-foreground]="!isImageSelected(image.id)"
            [disabled]="!isImageSelected(image.id) && selectedImages().length >= 2"
            (click)="toggleImageSelection(image)"
            type="button"
          >
            <img
              class="h-full w-full object-cover"
              [src]="image.thumbnail || '/placeholder.svg'"
              [alt]="image.title"
            />
            @if (isImageSelected(image.id)) {
              <div class="absolute inset-0 flex items-center justify-center bg-foreground/20">
                <div
                  class="flex items-center justify-center rounded-full bg-foreground p-1.5 text-background"
                >
                  <lucide-icon class="size-5" [img]="ICONS.Check" />
                </div>
              </div>
            }
          </button>
        }
      </div>

      <button class="w-full justify-center" (click)="loadMore()" appButton variant="secondary">
        Load More Images
      </button>
    </lib-card-content>
  </lib-card>

  <!-- Navigation -->
  <div class="flex justify-between gap-4">
    <button (click)="back.emit()" appButton variant="secondary">Back</button>
    <button [disabled]="selectedImages().length === 0" (click)="navigateNext()" appButton>
      {{ currentIndex() < totalCards() - 1 ? 'Next Card' : 'Review Flashcards' }}
    </button>
  </div>
</div>
