// apps/llaio/src/features/flashcard-generator/components/flashcard-preview.tsx
import type { Flashcard, NoteType, NoteTypeField } from '@/models/flashcard';

interface FlashcardPreviewProps {
  flashcard: Flashcard;
  noteType: NoteType;
  onClick: () => void;
}

function getWordFieldValue(flashcard: Flashcard, noteType: NoteType): string {
  const firstField = noteType.fields[0];

  if (!firstField) {
    return 'Untitled';
  }

  return flashcard.fieldValues[firstField.name] || 'Untitled';
}

function getPreviewFields(noteType: NoteType): NoteTypeField[] {
  return noteType.fields.filter((field, index) => index > 0 && field.fieldType !== 'image');
}

export function FlashcardPreview({ flashcard, noteType, onClick }: FlashcardPreviewProps) {
  const word = getWordFieldValue(flashcard, noteType);
  const previewFields = getPreviewFields(noteType)
    .map((field) => ({ field, value: flashcard.fieldValues[field.name] || '' }))
    .filter(({ value }) => value.trim().length > 0)
    .slice(0, 2);

  return (
    <button
      type="button"
      onClick={onClick}
      className="group w-full rounded-lg border border-border bg-card p-4 text-left transition-all duration-150 hover:border-border-hover hover:bg-accent-hover hover:shadow-sm"
      aria-label={`Edit flashcard for ${word}`}
    >
      <div className="space-y-3">
        <h3 className="text-heading-16 line-clamp-1 group-hover:text-foreground">{word}</h3>

        {flashcard.selectedImages.length > 0 ? (
          <div className="grid grid-cols-2 gap-2">
            {flashcard.selectedImages.slice(0, 2).map((image) => (
              <div key={image.id} className="overflow-hidden rounded-md border border-border">
                <img
                  src={image.thumbnail || image.url || '/placeholder.svg'}
                  alt={image.title}
                  className="h-20 w-full object-cover transition-transform duration-200 group-hover:scale-[1.02]"
                  loading="lazy"
                />
              </div>
            ))}
          </div>
        ) : null}

        {previewFields.map(({ field, value }) => (
          <div key={field.name} className="space-y-0.5">
            <p className="text-[11px] font-medium uppercase tracking-wider text-muted-foreground">
              {field.name}
            </p>
            <p className="text-foreground/80 line-clamp-2 text-[14px]">{value}</p>
          </div>
        ))}
      </div>
    </button>
  );
}

// src/app/features/flashcard-generator/components/flashcard-preview/flashcard-preview.component.ts
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';
import {
  CardComponent,
  CardContentDirective,
  CardHeaderDirective,
} from '../../../../shared/components/card/card.component';
import { Flashcard } from '../../models/flashcard.types';
import { NoteType } from '../../models/note-type.model';

@Component({
  selector: 'app-flashcard-preview',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [CardComponent, CardContentDirective, CardHeaderDirective],
  templateUrl: './flashcard-preview.component.html',
})
export class FlashcardPreviewComponent {
  public readonly flashcard = input.required<Flashcard>();

  public readonly noteType = input.required<NoteType>();

  public readonly compact = input(false);

  // Get the title field (marked with isTitle: true)
  protected readonly titleField = computed(() => this.noteType().fields.find((f) => f.isTitle));

  // Get displayable fields (exclude title and image fields)
  protected readonly displayFields = computed(() =>
    this.noteType().fields.filter((f) => !f.isTitle && f.fieldType !== 'image'),
  );
}

<lib-card [className]="'overflow-hidden ' + (compact() ? '' : 'max-w-md')">
  <lib-card-header>
    <span class="text-heading-20">
      <strong>{{ titleField() ? flashcard().fieldValues[titleField()!.name] : 'Untitled' }}</strong>
    </span>
  </lib-card-header>
  <lib-card-content class="flex flex-col gap-4 p-6">
    <!-- Images preview - 2 per row, small thumbnails -->
    @if (flashcard().selectedImages.length > 0) {
      <div class="grid grid-cols-2 gap-2">
        @for (image of flashcard().selectedImages; track image.id) {
          <div class="overflow-hidden rounded-lg border border-border bg-muted">
            <img
              class="block h-20 w-full object-cover"
              [src]="image.thumbnail || image.url || '/placeholder.svg'"
              [alt]="image.title"
            />
          </div>
        }
      </div>
    }

    <!-- Dynamic Fields -->
    @for (field of displayFields(); track field.name) {
      @if (flashcard().fieldValues[field.name]) {
        <div class="flex flex-col gap-1.5">
          <p class="m-0 text-xs font-medium tracking-wide text-muted-foreground uppercase">
            {{ field.name }}
          </p>
          <p [class]="'m-0 text-foreground ' + (compact() ? 'text-sm' : 'text-base')">
            {{ flashcard().fieldValues[field.name] }}
          </p>
        </div>
      }
    }
  </lib-card-content>
</lib-card>
