// src/features/flashcard-generator/components/export-flashcards-modal.tsx
import { useState } from 'react';

import { Button } from '@/components/ui/button';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Spinner } from '@/components/ui/spinner';
import type { Flashcard, NoteType } from '@/models/flashcard';
import { exportFlashcards } from '@/services/anki-export-service';

interface ExportFlashcardsModalProps {
  open: boolean;
  flashcards: Flashcard[];
  noteType: NoteType;
  onClose: () => void;
}

export function ExportFlashcardsModal({
  open,
  flashcards,
  noteType,
  onClose,
}: ExportFlashcardsModalProps) {
  const [deckName, setDeckName] = useState('LLAIO Flashcards');
  const [isExporting, setIsExporting] = useState(false);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [successMessage, setSuccessMessage] = useState<string | null>(null);

  const handleExport = async () => {
    const normalizedDeckName = deckName.trim();

    if (!normalizedDeckName) {
      setErrorMessage('Deck name is required.');
      setSuccessMessage(null);
      return;
    }

    setIsExporting(true);
    setErrorMessage(null);
    setSuccessMessage(null);

    try {
      await exportFlashcards(flashcards, noteType, normalizedDeckName);
      setSuccessMessage(`Exported ${flashcards.length} flashcards successfully.`);
    } catch (error) {
      const message = error instanceof Error ? error.message : 'Failed to export flashcards.';
      setErrorMessage(message);
    } finally {
      setIsExporting(false);
    }
  };

  const handleClose = () => {
    if (isExporting) {
      return;
    }

    setErrorMessage(null);
    setSuccessMessage(null);
    onClose();
  };

  return (
    <Dialog open={open} onOpenChange={(nextOpen) => !nextOpen && handleClose()}>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle>Export to Anki</DialogTitle>
          <DialogDescription>
            Configure deck name and export {flashcards.length} flashcards as .apkg.
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-3">
          <div className="space-y-2">
            <label htmlFor="deck-name" className="text-[14px] font-medium">
              Deck name
            </label>
            <Input
              id="deck-name"
              value={deckName}
              onChange={(event) => setDeckName(event.target.value)}
              placeholder="LLAIO Flashcards"
              disabled={isExporting}
            />
          </div>

          {errorMessage ? (
            <div className="border-destructive/20 bg-destructive/5 rounded-md border px-3 py-2.5 text-[14px] text-destructive">
              {errorMessage}
            </div>
          ) : null}
          {successMessage ? (
            <div className="border-success/20 bg-success/5 rounded-md border px-3 py-2.5 text-[14px] text-success">
              {successMessage}
            </div>
          ) : null}
        </div>

        <DialogFooter>
          <Button type="button" variant="outline" onClick={handleClose} disabled={isExporting}>
            Cancel
          </Button>
          <Button type="button" onClick={handleExport} disabled={isExporting}>
            {isExporting ? (
              <span className="inline-flex items-center gap-2">
                <Spinner size="sm" className="text-current" />
                Exporting…
              </span>
            ) : (
              'Export'
            )}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

// src/app/features/flashcard-generator/components/export-dialog/export-flashcards-modal.component.ts
import { ChangeDetectionStrategy, Component, inject, input, output, signal } from '@angular/core';
import { Download, LucideAngularModule } from 'lucide-angular';
import {
  ModalContentDirective,
  ModalFooterDirective,
} from '../../../../shared/components/modal/modal.component';
import { ButtonDirective } from '../../../../shared/directives/button/button.directive';
import { Flashcard } from '../../models/flashcard.types';
import { NoteType } from '../../models/note-type.model';
import { AnkiExportService } from '../../services/anki-export.service';

@Component({
  selector: 'app-export-flashcards-modal',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [ButtonDirective, LucideAngularModule, ModalContentDirective, ModalFooterDirective],
  templateUrl: './export-flashcards-modal.component.html',
})
export class ExportFlashcardsModal {
  private readonly ankiExportService = inject(AnkiExportService);

  // Constants
  protected readonly ICONS = {
    Download,
  };

  // Inputs
  public readonly flashcards = input<Flashcard[]>([]);

  public readonly noteType = input.required<NoteType>();

  // Outputs
  public readonly cancelExport = output();

  // State
  protected readonly isExporting = signal(false);

  protected readonly errorMessage = signal<string | null>(null);

  protected async handleExport() {
    this.isExporting.set(true);
    this.errorMessage.set(null);

    try {
      const deckName = this.noteType().deckName || this.noteType().name;
      await this.ankiExportService.exportToApkg(this.flashcards(), this.noteType(), deckName);
      this.cancelExport.emit();
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      this.errorMessage.set(message);
    } finally {
      this.isExporting.set(false);
    }
  }
}

<lib-modal-content class="flex flex-col items-center gap-6 py-4 text-center">
  <div class="flex size-16 items-center justify-center rounded-full bg-muted">
    <lucide-icon class="size-8 text-muted-foreground" [img]="ICONS.Download" />
  </div>

  <div class="flex flex-col gap-2">
    <h2 class="text-xl font-semibold">Export to Anki</h2>
    <p class="text-muted-foreground">
      Ready to export
      <span class="font-medium text-foreground">{{ flashcards().length }} flashcards</span>
      as an Anki deck (.apkg file).
    </p>
    @if (errorMessage()) {
      <p class="text-sm text-destructive">{{ errorMessage() }}</p>
    }
  </div>
</lib-modal-content>

<lib-modal-footer>
  <button [disabled]="isExporting()" (click)="cancelExport.emit()" appButton variant="secondary">
    Cancel
  </button>
  <button [disabled]="isExporting()" (click)="handleExport()" appButton>
    @if (isExporting()) {
      Exporting...
    } @else {
      Download .apkg
    }
  </button>
</lib-modal-footer>
