// src/app/core/layout/settings-modal/settings-modal.component.ts
import { ChangeDetectionStrategy, Component, inject, OnInit, output } from '@angular/core';
import { FormControl, ReactiveFormsModule } from '@angular/forms';
import { LucideAngularModule, Monitor, Moon, Sun, XIcon } from 'lucide-angular';
import {
  DropdownComponent,
  DropdownOption,
} from '../../../shared/components/dropdown/dropdown.component';
import {
  ModalContentDirective,
  ModalFooterDirective,
  ModalHeaderDirective,
} from '../../../shared/components/modal/modal.component';
import { ButtonDirective } from '../../../shared/directives/button/button.directive';
import { InputDirective } from '../../../shared/directives/input/input.directive';
import { Language, LANGUAGES, LanguageStore } from '../../stores/language.store';
import { SettingsStore } from '../../stores/settings.store';
import { Theme, ThemeStore } from '../../stores/theme.store';

// SVG path data for theme icons (Lucide icons)
const THEME_OPTIONS: DropdownOption[] = [
  {
    value: 'System',
    label: 'System',
    icon: Monitor,
  },
  {
    value: 'Light',
    label: 'Light',
    icon: Sun,
  },
  {
    value: 'Dark',
    label: 'Dark',
    icon: Moon,
  },
];

@Component({
  selector: 'app-settings-modal',
  imports: [
    ReactiveFormsModule,
    DropdownComponent,
    ButtonDirective,
    InputDirective,
    LucideAngularModule,
    ModalHeaderDirective,
    ModalContentDirective,
    ModalFooterDirective,
  ],
  templateUrl: './settings-modal.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class SettingsModalComponent implements OnInit {
  // Services
  private readonly settingsStore = inject(SettingsStore);

  private readonly languageStore = inject(LanguageStore);

  private readonly themeStore = inject(ThemeStore);

  // Constants
  protected readonly ICONS = {
    X: XIcon,
  };

  // Outputs
  public readonly closeModal = output();

  // Protected State
  protected readonly apiKeyControl = new FormControl('', { nonNullable: true });

  protected readonly googleCseApiKeyControl = new FormControl('', { nonNullable: true });

  protected readonly nativeLanguageControl = new FormControl<Language>('Vietnamese', {
    nonNullable: true,
  });

  protected readonly themeControl = new FormControl<Theme>('System', { nonNullable: true });

  protected readonly languages: Language[] = LANGUAGES;

  protected readonly themeOptions: DropdownOption[] = THEME_OPTIONS;

  public ngOnInit(): void {
    // Initialize form with stored values when component is created (modal opens)
    this.apiKeyControl.setValue(this.settingsStore.apiKey());
    this.googleCseApiKeyControl.setValue(this.settingsStore.googleCseApiKey());
    this.nativeLanguageControl.setValue(this.languageStore.nativeLanguage());
    this.themeControl.setValue(this.themeStore.theme());
  }

  protected onSave(): void {
    this.settingsStore.setApiKey(this.apiKeyControl.value);
    this.settingsStore.setGoogleCseApiKey(this.googleCseApiKeyControl.value);
    this.languageStore.setNativeLanguage(this.nativeLanguageControl.value);
    this.themeStore.setTheme(this.themeControl.value);
    this.closeModal.emit();
  }
}

<lib-modal-header>
  <h2 class="m-0 text-heading-24" id="settings-title">Settings</h2>
  <button
    class="-mt-2 -mr-2 inline-flex size-10 cursor-pointer items-center justify-center rounded-md border-transparent bg-transparent text-foreground-light transition-all duration-150 hover:bg-accent-hover hover:text-foreground"
    (click)="closeModal.emit()"
    aria-label="Close settings"
  >
    <lucide-icon class="size-5" [img]="ICONS.X" aria-hidden="true" />
  </button>
</lib-modal-header>

<lib-modal-content class="flex flex-col gap-4">
  <div class="flex flex-col">
    <label class="mb-2 block text-label-13" for="api-key">
      <strong>Gemini API Key</strong>
    </label>
    <input
      id="api-key"
      [formControl]="apiKeyControl"
      type="password"
      placeholder="Enter your API key"
      autocomplete="off"
      appInput
      spellcheck="false"
    />
    <p class="mt-2 text-label-13 text-muted-foreground">
      Your key is stored locally and never sent to our servers.
    </p>
  </div>

  <div class="flex flex-col">
    <label class="mb-2 block text-label-13" for="google-cse-key">
      <strong>Google Custom Search API Key</strong>
    </label>
    <input
      id="google-cse-key"
      [formControl]="googleCseApiKeyControl"
      type="password"
      placeholder="Enter your Google CSE API key"
      autocomplete="off"
      appInput
      spellcheck="false"
    />
    <p class="mt-2 text-label-13 text-muted-foreground">
      Used for image search in flashcard generation.
    </p>
  </div>

  <div class="flex flex-col">
    <label class="mb-2 block text-label-13" for="theme-select">
      <strong>Theme</strong>
    </label>
    <lib-dropdown
      [options]="themeOptions"
      [formControl]="themeControl"
      variant="full"
      align="left"
    />
  </div>

  <div class="flex flex-col">
    <label class="mb-2 block text-label-13" for="native-lang">
      <strong>Native Language</strong>
    </label>
    <lib-dropdown
      [options]="languages"
      [formControl]="nativeLanguageControl"
      variant="full"
      align="left"
    />
    <p class="mt-2 text-label-13 text-muted-foreground">
      Translations and explanations will be in this language.
    </p>
  </div>
</lib-modal-content>

<lib-modal-footer>
  <button (click)="onSave()" appButton>Save</button>
</lib-modal-footer>

// apps/llaio/src/components/layout/settings-modal.tsx
import { useEffect, useState } from 'react';
import { Monitor, Moon, Sun } from 'lucide-react';
import { useSettingsStore } from '@/stores/settings-store';
import { useLanguageStore, LANGUAGES } from '@/stores/language-store';
import { useThemeStore, THEMES } from '@/stores/theme-store';
import type { Language } from '@/stores/language-store';
import type { Theme } from '@/stores/theme-store';

import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from '@/components/ui/dialog';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';

export function SettingsModal() {
  const { apiKey, googleCseApiKey, isModalOpen, setApiKey, setGoogleCseApiKey, closeModal } =
    useSettingsStore();
  const { nativeLanguage, setNativeLanguage } = useLanguageStore();
  const { theme, setTheme } = useThemeStore();

  const [localApiKey, setLocalApiKey] = useState(apiKey);
  const [localGoogleCseApiKey, setLocalGoogleCseApiKey] = useState(googleCseApiKey);
  const [localTheme, setLocalTheme] = useState<Theme>(theme);
  const [localNativeLanguage, setLocalNativeLanguage] = useState<Language>(nativeLanguage);

  useEffect(() => {
    if (isModalOpen) {
      setLocalApiKey(apiKey);
      setLocalGoogleCseApiKey(googleCseApiKey);
      setLocalTheme(theme);
      setLocalNativeLanguage(nativeLanguage);
    }
  }, [isModalOpen, apiKey, googleCseApiKey, theme, nativeLanguage]);

  const handleSave = () => {
    setApiKey(localApiKey);
    setGoogleCseApiKey(localGoogleCseApiKey);
    setTheme(localTheme);
    setNativeLanguage(localNativeLanguage);
    closeModal();
  };

  return (
    <Dialog
      open={isModalOpen}
      onOpenChange={(open) => {
        if (!open) closeModal();
      }}
    >
      <DialogContent className="sm:max-w-[440px]">
        <DialogHeader>
          <DialogTitle className="text-heading-20 m-0">Settings</DialogTitle>
          <DialogDescription>
            Manage your API keys, preferred theme, and native language.
          </DialogDescription>
        </DialogHeader>

        <div className="flex flex-col gap-5 py-2">
          <div className="flex flex-col gap-2">
            <label className="text-[13px] font-medium text-foreground" htmlFor="api-key">
              Gemini API Key
            </label>
            <Input
              id="api-key"
              type="password"
              placeholder="Enter your API key"
              autoComplete="off"
              spellCheck={false}
              value={localApiKey}
              onChange={(e) => setLocalApiKey(e.target.value)}
            />
            <p className="text-[12px] leading-relaxed text-muted-foreground">
              Your key is stored locally and never sent to our servers.{' '}
              <a
                href="https://aistudio.google.com/app/apikey"
                target="_blank"
                rel="noopener noreferrer"
                className="decoration-muted-foreground/40 font-medium text-foreground underline underline-offset-4 transition-all hover:decoration-foreground"
              >
                Get API Key
              </a>
            </p>
          </div>

          <div className="flex flex-col gap-2">
            <label className="text-[13px] font-medium text-foreground" htmlFor="google-cse-key">
              Google Custom Search API Key
            </label>
            <Input
              id="google-cse-key"
              type="password"
              placeholder="Enter your Google CSE API key"
              autoComplete="off"
              spellCheck={false}
              value={localGoogleCseApiKey}
              onChange={(e) => setLocalGoogleCseApiKey(e.target.value)}
            />
            <p className="text-[12px] leading-relaxed text-muted-foreground">
              Used for image search in flashcard generation.{' '}
              <a
                href="https://programmablesearchengine.google.com/controlpanel/all"
                target="_blank"
                rel="noopener noreferrer"
                className="decoration-muted-foreground/40 font-medium text-foreground underline underline-offset-4 transition-all hover:decoration-foreground"
              >
                Get API Key
              </a>
            </p>
          </div>

          <div className="flex flex-col gap-2">
            <label className="text-[13px] font-medium text-foreground" htmlFor="theme-select">
              Theme
            </label>
            <Select value={localTheme} onValueChange={(val) => setLocalTheme(val as Theme)}>
              <SelectTrigger id="theme-select" className="w-full">
                <SelectValue placeholder="Select a theme" />
              </SelectTrigger>
              <SelectContent>
                {THEMES.map((t) => (
                  <SelectItem key={t} value={t}>
                    <div className="flex items-center gap-2.5">
                      {t === 'System' && <Monitor className="size-4 opacity-60" />}
                      {t === 'Light' && <Sun className="size-4 opacity-60" />}
                      {t === 'Dark' && <Moon className="size-4 opacity-60" />}
                      <span>{t}</span>
                    </div>
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          <div className="flex flex-col gap-2">
            <label className="text-[13px] font-medium text-foreground" htmlFor="native-lang">
              Native Language
            </label>
            <Select
              value={localNativeLanguage}
              onValueChange={(val) => setLocalNativeLanguage(val as Language)}
            >
              <SelectTrigger id="native-lang" className="w-full">
                <SelectValue placeholder="Select native language" />
              </SelectTrigger>
              <SelectContent>
                {LANGUAGES.map((lang) => (
                  <SelectItem key={lang} value={lang}>
                    {lang}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
            <p className="text-[12px] leading-relaxed text-muted-foreground">
              Translations and explanations will be in this language.
            </p>
          </div>
        </div>

        <DialogFooter className="mt-2 sm:items-center">
          <p className="text-muted-foreground/70 text-[12px] sm:mr-auto">
            Version {__APP_VERSION__}
          </p>
          <Button onClick={handleSave} className="w-full sm:w-auto">
            Save Changes
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
