// apps/llaio/src/features/word-definition/word-definition.tsx
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { marked } from 'marked';
import { Bookmark, RotateCcw, Volume2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { cn } from '@/lib/utils';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Spinner } from '@/components/ui/spinner';
import { generateDefinition } from '@/services/gemini-service';
import {
  addEntry,
  getCachedResponse,
  getHistory,
  type HistoryEntry,
} from '@/services/word-history-service';
import {
  isWordSaved,
  removeWord,
  saveWord,
  subscribeSavedWordsChanges,
} from '@/services/saved-words-service';
import { playPronunciation } from '@/services/pronunciation-service';
import { useLanguageStore, useSettingsStore } from '@/stores';
import { ContentStatus } from './content-status';

marked.setOptions({ async: false });

type DefinitionStatus = 'idle' | 'loading' | 'error' | 'success';

export function WordDefinition() {
  const { apiKey } = useSettingsStore();
  const { targetLanguage, nativeLanguage } = useLanguageStore();

  const [word, setWord] = useState('');
  const [definition, setDefinition] = useState('');
  const [status, setStatus] = useState<DefinitionStatus>('idle');
  const [error, setError] = useState<string | null>(null);
  const [history, setHistory] = useState<HistoryEntry[]>([]);
  const [isSaved, setIsSaved] = useState(false);
  const [saveError, setSaveError] = useState<string | null>(null);
  const [pronunciationError, setPronunciationError] = useState<string | null>(null);
  const [isPronunciationLoading, setIsPronunciationLoading] = useState(false);
  const [isPronunciationPlaying, setIsPronunciationPlaying] = useState(false);

  const abortControllerRef = useRef<AbortController | null>(null);
  const pronunciationAudioRef = useRef<HTMLAudioElement | null>(null);
  const pronunciationAudioUrlRef = useRef<string | null>(null);
  const pronunciationRequestRef = useRef(0);

  const historyWords = useMemo(() => {
    return history.map((entry) => entry.word);
  }, [history]);

  const markedHtml = useMemo(() => {
    if (!definition) {
      return '';
    }
    return marked.parse(definition) as string;
  }, [definition]);

  const releasePronunciationAudioUrl = useCallback(() => {
    if (!pronunciationAudioUrlRef.current) {
      return;
    }

    URL.revokeObjectURL(pronunciationAudioUrlRef.current);
    pronunciationAudioUrlRef.current = null;
  }, []);

  const stopPronunciationPlayback = useCallback(() => {
    const currentAudio = pronunciationAudioRef.current;
    if (currentAudio) {
      currentAudio.pause();
      currentAudio.currentTime = 0;
      currentAudio.onended = null;
      currentAudio.onerror = null;
      pronunciationAudioRef.current = null;
    }

    releasePronunciationAudioUrl();
    setIsPronunciationPlaying(false);
  }, [releasePronunciationAudioUrl]);

  const loadHistory = useCallback(() => {
    const entries = getHistory(targetLanguage, nativeLanguage);
    setHistory(entries);
  }, [targetLanguage, nativeLanguage]);

  useEffect(() => {
    loadHistory();
  }, [loadHistory]);

  useEffect(() => {
    const trimmedWord = word.trim();
    if (!trimmedWord) {
      setIsSaved(false);
      return;
    }

    setIsSaved(isWordSaved(trimmedWord, targetLanguage));
  }, [targetLanguage, word]);

  useEffect(
    () =>
      subscribeSavedWordsChanges(() => {
        const trimmedWord = word.trim();
        if (!trimmedWord) {
          return;
        }
        setIsSaved(isWordSaved(trimmedWord, targetLanguage));
      }),
    [targetLanguage, word],
  );

  useEffect(() => {
    return () => {
      pronunciationRequestRef.current += 1;
      abortControllerRef.current?.abort();
      stopPronunciationPlayback();
    };
  }, [stopPronunciationPlayback]);

  useEffect(() => {
    abortControllerRef.current?.abort();
    abortControllerRef.current = null;
    pronunciationRequestRef.current += 1;
    stopPronunciationPlayback();
    setWord('');
    setDefinition('');
    setError(null);
    setSaveError(null);
    setPronunciationError(null);
    setIsPronunciationLoading(false);
    setStatus('idle');
  }, [targetLanguage, nativeLanguage, stopPronunciationPlayback]);

  const runDefinition = async (inputWord: string) => {
    const trimmedWord = inputWord.trim();
    if (!trimmedWord) {
      return;
    }

    if (!apiKey) {
      setStatus('error');
      setError('Please configure your Google Gemini API key in Settings first.');
      return;
    }

    abortControllerRef.current?.abort();
    const controller = new AbortController();
    abortControllerRef.current = controller;

    setWord(trimmedWord);
    setStatus('loading');
    setError(null);
    setDefinition('');
    setPronunciationError(null);
    setIsPronunciationLoading(false);
    stopPronunciationPlayback();
    pronunciationRequestRef.current += 1;
    let streamedText = '';

    try {
      await generateDefinition(
        trimmedWord,
        apiKey,
        targetLanguage,
        nativeLanguage,
        (text) => {
          streamedText = text;
          setDefinition(text);
        },
        controller.signal,
      );

      if (controller.signal.aborted) {
        return;
      }

      setStatus('success');

      if (streamedText.trim().length > 0) {
        addEntry(trimmedWord, streamedText, targetLanguage, nativeLanguage);
        loadHistory();
      }
    } catch {
      if (controller.signal.aborted) {
        return;
      }

      setStatus('error');
      setError('Failed to fetch definition. Please check your API key and connection.');
    } finally {
      if (abortControllerRef.current === controller) {
        abortControllerRef.current = null;
      }
    }
  };

  const handleDefine = async () => {
    await runDefinition(word);
  };

  const handleReset = () => {
    abortControllerRef.current?.abort();
    abortControllerRef.current = null;
    pronunciationRequestRef.current += 1;
    stopPronunciationPlayback();
    setWord('');
    setDefinition('');
    setError(null);
    setSaveError(null);
    setPronunciationError(null);
    setIsPronunciationLoading(false);
    setStatus('idle');
  };

  const canSaveWord = status === 'success' && word.trim().length > 0;

  const handleToggleSavedWord = () => {
    if (!canSaveWord) {
      return;
    }

    const trimmedWord = word.trim();
    const result = isSaved
      ? removeWord(trimmedWord, targetLanguage)
      : saveWord(trimmedWord, targetLanguage);

    if (!result.ok) {
      setSaveError(result.error ?? 'Failed to update saved words.');
      return;
    }

    setSaveError(null);
    setIsSaved(!isSaved);
  };

  const handleSelectHistory = (selectedWord: string) => {
    abortControllerRef.current?.abort();
    abortControllerRef.current = null;
    pronunciationRequestRef.current += 1;
    stopPronunciationPlayback();
    setPronunciationError(null);
    setIsPronunciationLoading(false);
    setWord(selectedWord);
    const cached = getCachedResponse(selectedWord, targetLanguage, nativeLanguage);
    if (cached) {
      setDefinition(cached);
      setError(null);
      setStatus('success');
    }
  };

  const handlePlayPronunciation = async () => {
    const trimmedWord = word.trim();
    if (!trimmedWord || status !== 'success') {
      return;
    }

    const requestId = pronunciationRequestRef.current + 1;
    pronunciationRequestRef.current = requestId;

    setPronunciationError(null);
    setIsPronunciationLoading(true);
    stopPronunciationPlayback();

    const result = await playPronunciation(trimmedWord, targetLanguage);
    if (pronunciationRequestRef.current !== requestId) {
      if (result.audioUrl) {
        URL.revokeObjectURL(result.audioUrl);
      }
      return;
    }

    if (!result.ok || !result.audioUrl) {
      setIsPronunciationLoading(false);
      setIsPronunciationPlaying(false);
      setPronunciationError(
        result.error ?? 'Unable to play pronunciation audio right now. Please try again.',
      );
      return;
    }

    pronunciationAudioUrlRef.current = result.audioUrl;
    const audio = new Audio(result.audioUrl);
    pronunciationAudioRef.current = audio;

    audio.onended = () => {
      setIsPronunciationPlaying(false);
      pronunciationAudioRef.current = null;
      releasePronunciationAudioUrl();
    };

    audio.onerror = () => {
      setIsPronunciationPlaying(false);
      setPronunciationError('Unable to play pronunciation audio right now. Please try again.');
      pronunciationAudioRef.current = null;
      releasePronunciationAudioUrl();
    };

    try {
      await audio.play();
      setIsPronunciationPlaying(true);
    } catch {
      setIsPronunciationPlaying(false);
      setPronunciationError('Your browser blocked audio playback. Click again to retry.');
      pronunciationAudioRef.current = null;
      releasePronunciationAudioUrl();
    } finally {
      setIsPronunciationLoading(false);
    }
  };

  const showStreaming = status === 'loading' && definition.trim().length > 0;

  return (
    <div className="mx-auto flex max-w-3xl flex-col gap-6">
      {/* Search area */}
      <div className="flex flex-col gap-3">
        <div className="flex flex-col gap-2 sm:flex-row">
          <Input
            value={word}
            onChange={(event) => setWord(event.target.value)}
            onKeyDown={(event) => {
              if (event.key === 'Enter') {
                void handleDefine();
              }
            }}
            placeholder="e.g. Serendipity"
            className="h-11 flex-1 text-[15px]"
          />

          <div className="flex gap-2">
            <Button
              onClick={() => {
                void handleDefine();
              }}
              disabled={status === 'loading' || !word.trim()}
              className="relative h-11 flex-1 overflow-hidden transition-all sm:flex-initial sm:px-6"
            >
              <span
                className={cn(
                  'transition-all duration-300 ease-[cubic-bezier(0.16,1,0.3,1)]',
                  status === 'loading' ? 'scale-95 opacity-0' : 'scale-100 opacity-100',
                )}
              >
                Define
              </span>
              {status === 'loading' && (
                <div className="absolute inset-0 flex animate-fade-in items-center justify-center">
                  <Spinner size="sm" className="text-current" />
                </div>
              )}
            </Button>

            <Button
              variant="ghost"
              size="icon"
              onClick={handleReset}
              disabled={!word && !definition && status === 'idle'}
              className="h-11 w-11 shrink-0 transition-colors"
              aria-label="Reset"
            >
              <RotateCcw className="h-4 w-4 transition-transform active:-rotate-45" />
            </Button>

            <Button
              variant={isSaved ? 'secondary' : 'outline'}
              onClick={handleToggleSavedWord}
              disabled={!canSaveWord}
              className="relative h-11 px-3 transition-colors"
            >
              <span className="invisible flex items-center gap-2">
                <Bookmark className="h-4 w-4" />
                Save word
              </span>
              <div className="absolute inset-0 flex items-center justify-center gap-2">
                <Bookmark
                  className={cn(
                    'h-4 w-4 transition-all duration-300 ease-[cubic-bezier(0.16,1,0.3,1)]',
                    isSaved ? 'fill-current text-foreground' : 'fill-transparent',
                  )}
                />
                <span className="animate-fade-in">{isSaved ? 'Saved' : 'Save word'}</span>
              </div>
            </Button>
          </div>
        </div>

        {saveError ? (
          <div className="border-destructive/20 bg-destructive/5 animate-fade-in rounded-md border px-3 py-2.5 text-[14px] text-destructive">
            {saveError}
          </div>
        ) : null}

        {historyWords.length > 0 && (
          <div className="flex animate-fade-in">
            <Select onValueChange={handleSelectHistory}>
              <SelectTrigger className="h-9 w-full text-[13px] sm:w-64">
                <SelectValue placeholder="Recent words" />
              </SelectTrigger>
              <SelectContent>
                {historyWords.map((historyWord) => (
                  <SelectItem key={historyWord} value={historyWord}>
                    {historyWord}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
        )}
      </div>

      {/* Definition content */}
      <ContentStatus status={status} error={error} hasContent={definition.trim().length > 0}>
        <div className="border-border/60 animate-content-enter rounded-lg border bg-surface-raised p-6">
          <div className="border-border/40 mb-6 flex items-start justify-between gap-4 border-b pb-5">
            <div className="min-w-0 flex-1">
              <div className="flex items-center gap-3">
                <h2 className="truncate text-3xl font-bold tracking-tight text-foreground">
                  {word}
                </h2>
                <Button
                  type="button"
                  variant="ghost"
                  size="icon"
                  onClick={() => {
                    void handlePlayPronunciation();
                  }}
                  disabled={isPronunciationLoading || status !== 'success' || !word.trim()}
                  aria-label={`Play pronunciation for ${word.trim()}`}
                  title={`Pronounce in ${targetLanguage}`}
                  className={cn(
                    'h-10 w-10 shrink-0 rounded-full transition-all duration-300',
                    isPronunciationPlaying
                      ? 'bg-foreground text-background hover:bg-foreground/90'
                      : 'text-muted-foreground hover:bg-muted hover:text-foreground',
                  )}
                >
                  {isPronunciationLoading ? (
                    <Spinner size="sm" />
                  ) : (
                    <Volume2
                      className={cn(
                        'size-5 transition-transform duration-300',
                        isPronunciationPlaying && 'scale-110',
                      )}
                    />
                  )}
                </Button>
              </div>
              <p className="mt-1.5 text-[13px] font-medium text-muted-foreground">
                {targetLanguage} pronunciation
              </p>
            </div>
          </div>

          {pronunciationError ? (
            <div className="border-destructive/20 bg-destructive/5 mb-4 rounded-md border px-3 py-2 text-[13px] text-destructive">
              {pronunciationError}
            </div>
          ) : null}

          <div
            className="prose max-w-none dark:prose-invert prose-headings:tracking-tight prose-p:leading-relaxed prose-li:leading-relaxed"
            dangerouslySetInnerHTML={{ __html: markedHtml }}
          />
          {showStreaming && <span className="streaming-cursor" aria-hidden="true" />}
        </div>
      </ContentStatus>
    </div>
  );
}

// src/app/features/word-definition/word-definition.component.ts
import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { FormControl, ReactiveFormsModule } from '@angular/forms';
import { GeminiService } from '@core/services';
import { ButtonDirective, SpinnerComponent } from '@shared/components';
import { InputDirective } from '@shared/directives';
import { Clock, History, LucideAngularModule, Trash2, X } from 'lucide-angular';
import { marked } from 'marked';
import { ContentStatusComponent } from './components/content-status/content-status.component';
import { WordHistoryService } from './services/word-history.service';
@Component({
  selector: 'app-word-definition',
  imports: [
    ReactiveFormsModule,
    SpinnerComponent,
    LucideAngularModule,
    ContentStatusComponent,
    ButtonDirective,
    InputDirective,
  ],
  templateUrl: './word-definition.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class WordDefinitionComponent {
  // Services
  private readonly geminiService = inject(GeminiService);

  private readonly wordHistoryService = inject(WordHistoryService);

  // Constants
  protected readonly ICONS = {
    X,
    History,
    Trash2,
    Clock,
  };

  // Public Properties
  public readonly searchControl = new FormControl<string>('', { nonNullable: true });

  // Protected State
  protected readonly definition = signal<string>('');

  protected readonly isLoading = signal(false);

  protected readonly isStreaming = signal(false);

  protected readonly error = signal<string | null>(null);

  protected readonly historyOpen = signal(false);

  protected readonly searchHistory = this.wordHistoryService.history;

  public async onSearch(word: string | null = null) {
    const searchTerm = word || this.searchControl.value;
    if (!searchTerm.trim()) return;

    // Update input if coming from history click
    this.searchControl.setValue(searchTerm);
    this.historyOpen.set(false);

    this.error.set(null);

    // Check for cached response first to save tokens
    const cachedResponse = this.wordHistoryService.getCachedResponse(searchTerm);
    if (cachedResponse) {
      this.definition.set(cachedResponse);
      return;
    }

    this.isLoading.set(true);
    this.isStreaming.set(true);
    this.definition.set('');

    let lastParsed = '';
    this.geminiService.generateDefinition(searchTerm).subscribe({
      next: async (result) => {
        const parsed = await marked.parse(result, { breaks: true });
        this.definition.set(parsed);
        lastParsed = parsed;
        this.isLoading.set(false);
      },
      error: (err) => {
        console.error('Gemini API Error:', err);
        this.error.set('Failed to fetch definition. Please check your API key and connection.');
        this.isLoading.set(false);
        this.isStreaming.set(false);
      },
      complete: () => {
        this.isStreaming.set(false);
        // Save final response to history for future lookups
        this.wordHistoryService.addToHistory(searchTerm, lastParsed);
      },
    });
  }

  public onReset() {
    this.searchControl.setValue('');
    this.definition.set('');
    this.error.set(null);
  }

  public clearHistory() {
    this.wordHistoryService.clearHistory();
    this.historyOpen.set(false);
  }

  protected toggleHistory(): void {
    this.historyOpen.update((v) => !v);
  }
}

<div class="mx-auto flex max-w-200 flex-col gap-6">
  <div class="w-full">
    <div class="relative rounded-lg border border-border bg-background p-6 shadow-sm">
      <div class="flex flex-col gap-4">
        <div class="flex flex-col">
          <label class="text-label-14" for="word-search">Enter a word</label>
          <div class="relative mt-1 flex items-center">
            <input
              class="h-12"
              id="word-search"
              [formControl]="searchControl"
              (keyup.enter)="onSearch()"
              appInput
              placeholder="e.g. Serendipity"
              autocomplete="off"
            />
            @if (searchControl.value) {
              <button
                class="absolute right-2 inline-flex size-8 cursor-pointer items-center justify-center rounded-md border-transparent bg-transparent text-muted-foreground transition-all duration-150 hover:bg-muted"
                (click)="searchControl.setValue('')"
                aria-label="Clear"
              >
                <lucide-icon class="size-4" [img]="ICONS.X" />
              </button>
            }
          </div>
        </div>

        <div class="flex items-center gap-3">
          <button
            [disabled]="isLoading() || !searchControl.value"
            (click)="onSearch()"
            appButton
            variant="default"
            size="default"
          >
            @if (isLoading()) {
              <lib-spinner size="sm" variant="contrast" />
            } @else {
              Define
            }
          </button>

          <button
            [disabled]="isLoading()"
            (click)="onReset()"
            appButton
            variant="secondary"
            size="default"
          >
            Reset
          </button>

          <!-- History Dropdown -->
          <div class="relative ml-auto">
            <button
              class="inline-flex size-10 cursor-pointer items-center justify-center rounded-md border-transparent bg-muted text-foreground transition-all duration-150 hover:bg-accent-active disabled:cursor-not-allowed disabled:opacity-50"
              [attr.aria-expanded]="historyOpen()"
              [disabled]="searchHistory().length === 0"
              (click)="toggleHistory()"
              (keydown.escape)="historyOpen.set(false)"
              aria-label="Search History"
              title="Search History"
              aria-haspopup="listbox"
            >
              <lucide-icon class="size-5" [img]="ICONS.History" />
            </button>

            @if (historyOpen()) {
              <div
                class="absolute top-[calc(100%+8px)] right-0 z-50 w-70 overflow-hidden rounded-lg border border-border bg-background shadow-lg"
                role="listbox"
              >
                <div
                  class="flex items-center justify-between border-b border-border bg-muted px-4 py-3 text-[13px] font-medium text-muted-foreground"
                >
                  <span>Search History</span>
                  <button
                    class="inline-flex size-7 cursor-pointer items-center justify-center rounded-md border-transparent bg-transparent text-muted-foreground transition-all duration-150 hover:text-destructive"
                    (click)="clearHistory(); $event.stopPropagation()"
                    (keydown.escape)="historyOpen.set(false)"
                    aria-label="Clear History"
                    title="Clear History"
                  >
                    <lucide-icon class="size-4" [img]="ICONS.Trash2" />
                  </button>
                </div>
                <div class="max-h-75 overflow-y-auto p-1">
                  @for (word of searchHistory(); track word) {
                    <button
                      class="flex w-full cursor-pointer items-center gap-3 rounded-md border-none bg-transparent px-3 py-2 text-left text-sm text-foreground transition-colors duration-150 hover:bg-muted"
                      (click)="onSearch(word)"
                      (keydown.escape)="historyOpen.set(false)"
                      role="option"
                      aria-selected="false"
                    >
                      <lucide-icon class="size-4 text-muted-foreground" [img]="ICONS.Clock" />
                      <span>{{ word }}</span>
                    </button>
                  }
                </div>
              </div>
              <div
                class="fixed inset-0 z-40 cursor-default"
                (click)="historyOpen.set(false)"
                aria-hidden="true"
              ></div>
            }
          </div>
        </div>
      </div>
    </div>
  </div>

  <app-content-status [isLoading]="isLoading()" [error]="error()" [isEmpty]="!definition()">
    <div class="relative rounded-lg border border-border bg-background p-6 shadow-sm">
      <article
        class="prose [--tw-prose-body:var(--foreground)] [--tw-prose-bold:var(--foreground)] dark:prose-invert prose-headings:text-heading-24 prose-headings:leading-[inherit] prose-p:text-copy-16 prose-p:leading-[inherit] prose-strong:text-foreground prose-li:text-label-16 prose-li:leading-[inherit]"
        [innerHTML]="definition()"
      ></article>
      @if (isStreaming()) {
        <span class="streaming-cursor" aria-hidden="true"></span>
      }
    </div>
  </app-content-status>
</div>
