// src/app/shared/components/card/card.component.ts
import { ChangeDetectionStrategy, Component, Directive, input } from '@angular/core';
@Directive({
  selector: 'lib-card-header, [libCardHeader]',
  host: {
    class: 'flex flex-col space-y-1.5 p-6',
  },
})
export class CardHeaderDirective {}

@Directive({
  selector: 'lib-card-title, [libCardTitle]',
  host: {
    class: 'leading-none font-semibold tracking-tight',
  },
})
export class CardTitleDirective {}

@Directive({
  selector: 'lib-card-description, [libCardDescription]',
  host: {
    class: 'text-sm text-muted-foreground',
  },
})
export class CardDescriptionDirective {}

@Directive({
  selector: 'lib-card-content, [libCardContent]',
  host: {
    class: 'p-6 pt-0',
  },
})
export class CardContentDirective {}

@Directive({
  selector: 'lib-card-footer, [libCardFooter]',
  host: {
    class: 'flex items-center p-6 pt-0',
  },
})
export class CardFooterDirective {}

@Component({
  selector: 'lib-card',
  changeDetection: ChangeDetectionStrategy.OnPush,
  templateUrl: './card.component.html',
})
export class CardComponent {
  public readonly className = input('');
}

<div
  [class]="
    'rounded-xl bg-background text-card-foreground shadow-sm ring ring-border ' + className()
  "
>
  <ng-content></ng-content>
</div>

// src/components/ui/card.tsx
import * as React from 'react';

import { cn } from '@/lib/utils';

const Card = React.forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement>>(
  ({ className, ...props }, ref) => (
    <div
      ref={ref}
      className={cn(
        'rounded-lg border border-border bg-card text-card-foreground transition-colors',
        className,
      )}
      {...props}
    />
  ),
);
Card.displayName = 'Card';

const CardHeader = React.forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement>>(
  ({ className, ...props }, ref) => (
    <div ref={ref} className={cn('flex flex-col space-y-1.5 p-5 pb-0', className)} {...props} />
  ),
);
CardHeader.displayName = 'CardHeader';

const CardTitle = React.forwardRef<HTMLParagraphElement, React.HTMLAttributes<HTMLHeadingElement>>(
  ({ className, ...props }, ref) => (
    <h2
      ref={ref}
      className={cn('text-lg font-semibold leading-none tracking-tight', className)}
      {...props}
    />
  ),
);
CardTitle.displayName = 'CardTitle';

const CardDescription = React.forwardRef<
  HTMLParagraphElement,
  React.HTMLAttributes<HTMLParagraphElement>
>(({ className, ...props }, ref) => (
  <p ref={ref} className={cn('text-[14px] text-muted-foreground', className)} {...props} />
));
CardDescription.displayName = 'CardDescription';

const CardContent = React.forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement>>(
  ({ className, ...props }, ref) => (
    <div ref={ref} className={cn('p-5 pt-4', className)} {...props} />
  ),
);
CardContent.displayName = 'CardContent';

const CardFooter = React.forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement>>(
  ({ className, ...props }, ref) => (
    <div ref={ref} className={cn('flex items-center p-5 pt-0', className)} {...props} />
  ),
);
CardFooter.displayName = 'CardFooter';

export { Card, CardHeader, CardFooter, CardTitle, CardDescription, CardContent };
